baseURL = "https://joshbutts.com/"
languageCode = "en-us"
title = "Josh Butts | joshbutts.com"
theme = "hugo-coder"
publishDir = "docs"
googleAnalytics = "UA-158918590-1"
canonifyurls = true
pygmentsstyle = "b2"
pygmentscodefences = true
pygmentscodefencesguesssyntax = true


[params]
    author = "Josh Butts"
    description = "Personal website of Josh Butts"
    keywords = "blog,developer,personal"
    info = "Technology Leader & Digital Media Executive"
    avatarurl = "/images/headshot-480.jpg"
    hideCredits = true


[taxonomies]
  tag = "tags"

[[params.social]]
    name = "Github"
    icon = "fab fa-github"
    weight = 1
    url = "https://github.com/jimbojsb/"

[[params.social]]
    name = "Twitter"
    icon = "fab fa-twitter"
    weight = 1
    url = "https://twitter.com/jimbojsb/"

[[params.social]]
    name = "LinkedIn"
    icon = "fab fa-linkedin"
    weight = 1
    url = "https://www.linkedin.com/in/joshbutts"

[[params.social]]
    name = "Instagram"
    icon = "fab fa-instagram"
    weight = 1
    url = "https://www.instagram.com/jimbojsb/"

[languages]
    [languages.en]
        languagename = "English"
        [languages.en.menu]
            [[languages.en.menu.main]]
            name = "Blog"
            weight = 1
            url = "posts/"
